.TH dvd+rw-mediainfo 1 "April 2004"
.SH NAME
dvd+rw-mediainfo \- display information about dvd drive and disk

.SH SYNOPSIS
.B dvd+rw\-mediainfo
.I /dev/dvd

.SH DESCRIPTION
The
.B dvd+rw\-mediainfo
command displays information about the drive and disk in the specified dvd
drive (e.g. \fI/dev/dvd\fR). This is especially useful for debugging
purposes and it is requested that its output be included when reporting bugs
found in the \fBdvd+rw\-tools\fI package.

.SH OPTIONS
.TP
This program does not accept any command line options.

.SH SEE ALSO
Most up-to-date information on dvd+rw\-tools is available at
http://fy.chalmers.se/~appro/linux/DVD+RW/.
.PP
The manpage for \fBgenisofs\fP(8),  \fBgrowisofs\fP(1),
\fBdvd+rw\-format\fP(1), \fBdvd+rw\-booktype\fP(1).

.SH AUTHOR
\fBdvd+rw\-mediainfo\fR was written by Andy Polyakov <appro@fy.chalmers.se>.
This manual page was written by Thomas Viehmann <tv@beamnet.de>
for the Debian project.
