.TH DVD-RAM-CONTROL "1" "February 2010" "dvd+rw\-tools" "User Commands"
.SH NAME
dev\-ram\-control \- checks features of DVD-RAM discs

.SH SYNOPSIS
.B dvd\-ram\-control
[\-arre] [\-awre] [\-rdonly|\-rdwr]
.I /dev/dvd

.SH DESCRIPTION
The
.B dvd\-ram\-control
command allows the user to check/set features of DVD-RAM discs. One such
information is the Persistent Write Protection, controlling if the disc
can be in read-only mode or if both reads and writes are enabled. It
also allows the user to check and or set if Automatic Write Relocation
Enable (AWRE) as well as Automatic Read Relocation Enable (ARRE) are
enabled or not for a given media.

.SH "SEE ALSO"
Most up\-to\-date information on dvd+rw\-tools is available at
http://fy.chalmers.se/~appro/linux/DVD+RW/.
.PP
The manpage for \fBgrowisofs\fP(1), \fBdvd+rw\-format\fP(1),
\fBdvd+rw\-booktype\fP(1).

.SH AUTHOR
\fBdvd+rw\-mediainfo\fR was written by Andy Polyakov <appro@fy.chalmers.se>.
This manual page was written by Rog\['e]rio Brito <rbrito@ime.usp.br>
for the Debian project, but it may be used by others.
